apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go-api
  labels:
    app: example-go-api
spec:
  selector:
    matchLabels:
      app: example-go-api
  template:
    metadata:
      labels:
        app: example-go-api
    spec:
      containers:
        - name: example-go-api
          image: example-go-api-image
          ports:
            - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: example-go-api
spec:
  selector:
    app: example-go-api
  ports:
    - name: example-go-api
      port: 3333
      targetPort: 3333
      protocol: TCP
